<a href="https://colab.research.google.com/github/hrtywhy/Machine-Learning/blob/main/KNN%20-%20Regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**KNN untuk permasalahan Regresi**

KNN regression is a non-parametric method that, in an intuitive manner, approximates the association between independent variables and the continuous outcome by averaging the observations in the same neighbourhood. The size of the neighbourhood needs to be set by the analyst or can be chosen using cross-validation (we will see this later) to select the size that minimises the mean-squared error.

In [29]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


import dataset from drive 



In [32]:
path = "/content/drive/My Drive/Dataset/regresi.csv"
data = pd.read_csv(path)
array = data.values
X = array[:,:2]
Y = array[:,:-1]
data.shape


(10, 2)

show data `X` and `Y`

In [33]:
data.head(10)

Berat Badan(gr/ekor)  Harga
0                  2000     40
1                  1000     20
2                  3000     60
3                  6000    120
4                 78000   1560
5                111000   2220
6                 88000   1760
7                  7000    140
8                 92000   1840
9                 45000    900

In [34]:
X

array([[  2000,     40],
       [  1000,     20],
       [  3000,     60],
       [  6000,    120],
       [ 78000,   1560],
       [111000,   2220],
       [ 88000,   1760],
       [  7000,    140],
       [ 92000,   1840],
       [ 45000,    900]])

In [49]:
Y

array([[  2000],
       [  1000],
       [  3000],
       [  6000],
       [ 78000],
       [111000],
       [ 88000],
       [  7000],
       [ 92000],
       [ 45000]])

  Bagi data menjadi 60 % training dan 40% testing 
  

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)

Misalkan y = yang harus diperkirakan adalah "Compressive Strength (28-day)(Mpa)" 

masukan X ADALAH KOLOM : Cement,Slag,Fly ash,Water,SP,Coarse Aggr.,Fine Aggr.,SLUMP(cm),FLOW(cm)

Kita akan menggunakan KNN untuk melakukan regresi dengan mengimport library KNN regresi sebagai berikut 


In [68]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 6)
knnr.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                    weights='uniform')

Menampilkan error y hasil prediksi 

dan y test 

In [69]:
y_predict = knnr.predict(X_test)
y_predict



array([[44833.33333333],
       [44833.33333333],
       [44833.33333333],
       [44833.33333333]])

In [70]:
y_test

array([[  7000],
       [  1000],
       [ 45000],
       [111000]])

Menampilkan Mean square Error 

In [71]:
print ("The MSE is:",format(np.power(y_test-y_predict,2).mean()))

The MSE is: 1932694444.4444442
